extends:
    - airbnb-base
    - plugin:prettier/recommended
    - 'plugin:jest/recommended'

plugins:
    - jest
    - prettier
    - js-yaml

env:
    node: true
    jest: true

parserOptions:
    ecmaVersion: latest
    sourceType: module

rules:
    no-console: 0
    import/extensions:
        - error
        - ignorePackages
        - js: always
    no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
